[tool.poetry]
name = "hadoop-fs-wrapper"
version = "0.0.0"
description = "Python Wrapper for Hadoop Java API"
authors = ["ECCO Sneaks & Data <esdsupport@ecco.com>"]
maintainers = ['GZU <gzu@ecco.com>', 'JRB <ext-jrb@ecco.com>']
license = 'MIT'
readme = "README.md"
repository = 'https://github.com/SneaksAndData/hadoop-fs-wrapper'

[tool.poetry.dependencies]
python = "^3.8"
pyspark = "~3.3"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-cov = "^2.12"
pylint = "^2.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
